server:
  port: 8082

spring:
  application:
    name: customer-ql-svc

  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/customerdb?authSource=admin

  graphql:
    schema:
      locations: classpath:schema/
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql
    websocket:
      path: /graphql
